package com.trithuc.service.impl;

import com.trithuc.dataStructures.Trie;
import com.trithuc.service.AutocompleteService;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class AutocompleteServiceImpl implements AutocompleteService {


    private final Trie trie;

    public AutocompleteServiceImpl(){
        trie = new Trie();
        trie.insert("Hạ Long Bay");
        trie.insert("Hội An Ancient Town");
        trie.insert("Phong Nha-Kẻ Bàng National Park");
        trie.insert("Sapa");
        trie.insert("Nha Trang Beach");
        trie.insert("Đà Lạt");
        trie.insert("Mekong Delta");
        trie.insert("Côn Đảo Islands");
        trie.insert("Hồ Chí Minh City");
        trie.insert("Hà Nội");
        trie.insert("Hue Imperial City");
        trie.insert("Tam Coc");
        trie.insert("Ba Bể Lake");
        trie.insert("Cát Bà Island");
        trie.insert("Phú Quốc Island");
        trie.insert("Bái Đính Pagoda");
        trie.insert("Mai Châu Valley");
        trie.insert("My Son Sanctuary");
        trie.insert("Bà Nà Hills");
        trie.insert("Golden Bridge Đà Nẵng");
        trie.insert("Saigon Notre-Dame Basilica");
        trie.insert("Cu Chi Tunnels");
        trie.insert("Hàm Rồng Mountain");
        trie.insert("Langbiang Mountain");
        trie.insert("Cai Rang Floating Market");
        trie.insert("Phong Nha Cave");
        trie.insert("Thác Bản Giốc Waterfall");
        trie.insert("Đảo Lý Sơn");
        trie.insert("Mũi Né Sand Dunes");
        trie.insert("Tràng An Scenic Landscape Complex");
        trie.insert("Đồng Văn Plateau");
        trie.insert("Mộc Châu");
        trie.insert("Nam Cát Tiên National Park");
        trie.insert("Yok Đôn National Park");
        trie.insert("Phan Rang-Tháp Chàm");
        trie.insert("Quy Nhơn Beach");
        trie.insert("Vũng Tàu");
        trie.insert("Cần Thơ");
        trie.insert("Bà Đen Mountain");
        trie.insert("Ninh Bình");
        trie.insert("Tây Ninh Holy See");
        trie.insert("Côn Đảo Prison Museum");
        trie.insert("Buôn Ma Thuột");
        trie.insert("Đắk Lắk");
        trie.insert("Tà Đùng Lake");
        trie.insert("Làng Cổ Phong Nha");
        trie.insert("Tháp Bà Ponagar");
        trie.insert("Hòn Mun Island");
        trie.insert("Vườn Quốc Gia Ba Vì");
        trie.insert("Chùa Hương");
        trie.insert("Cát Tiên National Park");
        trie.insert("Suối Tranh Waterfall");
        trie.insert("Đảo Bình Ba");
        trie.insert("Đà Nẵng");
        trie.insert("Bãi biển Mỹ Khê");
        trie.insert("Thành phố Vũng Tàu");
        trie.insert("Biển An Bàng");
        trie.insert("Đồi cát Trắng Mũi Né");
        trie.insert("Chùa Linh Ứng Đà Nẵng");
        trie.insert("Chùa Một Cột Hà Nội");
        trie.insert("Cầu Nhật Tân");
        trie.insert("Chợ Bến Thành");
        trie.insert("Đảo Cô Tô");
        trie.insert("Đầm Ô Loan");
        trie.insert("Vườn quốc gia Cúc Phương");
        trie.insert("Thành cổ Quảng Trị");
        trie.insert("Làng chài Cửa Vạn");
        trie.insert("Hòn Chồng Nha Trang");
        trie.insert("Bãi biển Mỹ Sơn");
        trie.insert("Cố đô Hoa Lư Ninh Bình");
        trie.insert("Chùa Thiên Mụ");
        trie.insert("Núi Chúa Phú Yên");
        trie.insert("Làng gốm Bát Tràng");
        trie.insert("Tháp Chăm Ninh Thuận");
        trie.insert("Đảo Bình Hưng");
        trie.insert("Vườn quốc gia Tràm Chim");
        trie.insert("Làng nổi Tân Lập");
        trie.insert("Thác Giang Điền");
        trie.insert("Thác Dambri Bảo Lộc");
        trie.insert("Rừng tràm Trà Sư An Giang");
        trie.insert("Vườn quốc gia U Minh Thượng");
        trie.insert("Núi Hàm Rồng Sapa");
        trie.insert("Thung lũng Bắc Sơn");
        trie.insert("Đèo Hải Vân");
        trie.insert("Hà Giang");
        trie.insert("Cánh đồng quạt gió Bạc Liêu");
        trie.insert("Bình Châu Hot Spring");
        trie.insert("Suối tiên Mũi Né");
        trie.insert("Bãi Sao Phú Quốc");
        trie.insert("Biển Hồ Cốc");
        trie.insert("Đồi Chè Mộc Châu");
        trie.insert("Đền Thờ Thánh Gióng");
        trie.insert("Thành cổ Sơn Tây");
        trie.insert("Rừng Nguyên Sinh Tam Đảo");
        trie.insert("Đồi thông hai mộ Đà Lạt");
        trie.insert("Thác Prenn Đà Lạt");
        trie.insert("Biển Bình Tiên Ninh Thuận");
        trie.insert("Đồi cát Hồng Mũi Né");
        trie.insert("Nhà thờ Gỗ Kon Tum");
        trie.insert("Làng văn hóa các dân tộc Tây Nguyên");
        trie.insert("Thác K50");
        trie.insert("Đền Hùng Phú Thọ");
        trie.insert("Làng chài Nhơn Lý");
        trie.insert("Bãi tắm đôi Nha Trang");
        trie.insert("Đảo Ngọc Vừng");
        trie.insert("Động Thiên Đường");
        trie.insert("Núi Cấm An Giang");
        trie.insert("Thác Bảo Đại Lâm Đồng");
        trie.insert("Làng văn hóa 54 dân tộc Việt Nam");
        trie.insert("Đèo Ngang Hà Tĩnh");
        trie.insert("Chùa Bái Đính Ninh Bình");
        trie.insert("Suối nước nóng Kim Bôi");
        trie.insert("Thác Bản Giốc Cao Bằng");
        trie.insert("Đảo Ngũ Chỉ Sơn");
        trie.insert("Thành phố Quy Nhơn Bình Định");
        trie.insert("Núi Lang Biang Đà Lạt");
        trie.insert("Khu du lịch Bà Nà Hills");
        trie.insert("Làng cổ Phú An");
        trie.insert("Núi Bà Đen Tây Ninh");
        trie.insert("Chợ nổi Phụng Hiệp");
        trie.insert("Hồ Thác Bà");
        trie.insert("Đèo Khánh Lê");
        trie.insert("Biển Lăng Cô Huế");
        trie.insert("Suối Mơ");
        trie.insert("Thác Dray Nur Đắk Lắk");
        trie.insert("Núi Chứa Chan Đồng Nai");
        trie.insert("Hòn Yến Phú Yên");
        trie.insert("Núi Tà Xùa Sơn La");
        trie.insert("Thành phố Phan Rang Tháp Chàm");
        trie.insert("Vườn quốc gia Xuân Thủy");
        trie.insert("Động Phong Nha");
        trie.insert("Hồ Tà Đùng");
        trie.insert("Đồi hoa tam giác mạch Hà Giang");
        trie.insert("Rừng Thông Bản Áng");
        trie.insert("Chùa Bửu Long Sài Gòn");
        trie.insert("Chợ đêm Đà Lạt");
        trie.insert("Biển Mỹ Khê Đà Nẵng");
        trie.insert("Bãi Dài Phú Quốc");
        trie.insert("Hòn Móng Tay Phú Quốc");
        trie.insert("Rừng tràm Tân Lập Long An");
        trie.insert("Thác Mơ Đắk Lắk");
        trie.insert("Làng hoa Sa Đéc");
        trie.insert("Lăng Khải Định Huế");
        trie.insert("Làng chài Hàm Ninh Phú Quốc");
        trie.insert("Động Hương Tích");
        trie.insert("Khu du lịch sinh thái Tràng An");
        trie.insert("Biển Kỳ Co Bình Định");
        trie.insert("Thành phố Nha Trang");
        trie.insert("Bãi Trước Vũng Tàu");
        trie.insert("Công viên nước Hồ Tây");
        trie.insert("Cù Lao Chàm Quảng Nam");
        trie.insert("Đảo Lý Sơn Quảng Ngãi");
        trie.insert("Cầu Thê Húc");
        trie.insert("Suối Giải Oan Yên Tử");
        trie.insert("Cầu Bàn Tay Bà Nà Hills");
        trie.insert("Vịnh Lan Hạ Hải Phòng");
        trie.insert("Hồ Núi Cốc Thái Nguyên");
        trie.insert("Vườn quốc gia Phú Quốc");
        trie.insert("Vịnh Bái Tử Long");
        trie.insert("Làng nổi Châu Đốc");
        trie.insert("Rừng U Minh Hạ");
        trie.insert("Đồng Văn Hà Giang");
        trie.insert("Phố cổ Đồng Văn");
        trie.insert("Núi Ngự Bình Huế");
        trie.insert("Chợ tình Khâu Vai Hà Giang");
        trie.insert("Bãi Dài Cam Ranh");
        trie.insert("Thác Ba Tầng Bảo Lộc");
        trie.insert("Thác Pongour Đà Lạt");
        trie.insert("Núi Yên Tử Quảng Ninh");
        trie.insert("Đồi cát Mũi Né");
        trie.insert("Động Am Tiên Ninh Bình");
        trie.insert("Khu du lịch Đại Nam Bình Dương");
        trie.insert("Lăng Tự Đức Huế");
        trie.insert("Hồ Tây Hà Nội");
        trie.insert("Làng nổi Phước Kiều");
        trie.insert("Vườn quốc gia Pù Mát Nghệ An");
        trie.insert("Bãi Xép Phú Yên");
        trie.insert("Cầu Tình Yêu Đà Nẵng");
        trie.insert("Làng bích họa Tam Thanh");
        trie.insert("Đồi chè Đông Giang Quảng Nam");
        trie.insert("Vịnh Vĩnh Hy Ninh Thuận");
        trie.insert("Làng lụa Vạn Phúc Hà Nội");
        trie.insert("Núi Bà Đen Tây Ninh");
        trie.insert("Bảo tàng Dân tộc học Hà Nội");
        trie.insert("Chợ đêm Hạ Long");
        trie.insert("Biển Hải Tiến Thanh Hóa");
        trie.insert("Suối Lạnh Đà Lạt");
        trie.insert("Cầu Gỗ Ô Cấp Vũng Tàu");
        trie.insert("Thác Lưu Ly Bình Phước");
        trie.insert("Biển Hồ Pleiku");
        trie.insert("Suối Tranh Phú Quốc");
        trie.insert("Đỉnh Fansipan Sapa");
        trie.insert("Đồi thông Mộc Châu");
        trie.insert("Thác Nước Yang Bay Khánh Hòa");
        trie.insert("Đồi cát Hòn Rơm");
        trie.insert("Thành phố Hạ Long");
        trie.insert("Cầu Quay Sông Hàn Đà Nẵng");
        trie.insert("Đền Ngọc Sơn Hà Nội");
        trie.insert("Chợ Hàn Đà Nẵng");
        trie.insert("Đảo Nam Du Kiên Giang");
        trie.insert("Hồ Tuyền Lâm Đà Lạt");
        trie.insert("Bảo tàng Hồ Chí Minh");
        trie.insert("Vườn quốc gia Bạch Mã Huế");
        trie.insert("Đảo Hòn Tằm Nha Trang");
        trie.insert("Núi Cấm An Giang");
        trie.insert("Hồ Xuân Hương Đà Lạt");
        trie.insert("Chợ Đầm Nha Trang");
        trie.insert("Suối Tiên Hồ Chí Minh");
        trie.insert("Vườn quốc gia Ba Bể Bắc Kạn");
        trie.insert("Bảo tàng Áo dài Sài Gòn");
        trie.insert("Chùa Từ Đàm Huế");
        trie.insert("Cầu Rồng Đà Nẵng");
        trie.insert("Khu sinh thái Tam Cốc Bích Động");
        trie.insert("Đền Lý Nam Đế Phú Thọ");
        trie.insert("Khu phố Tây Phạm Ngũ Lão");
        trie.insert("Thành phố Hội An Quảng Nam");
        trie.insert("Bãi biển Lăng Cô Huế");
        trie.insert("Đảo Bình Ba Khánh Hòa");
        trie.insert("Chùa Hương Hà Nội");
        trie.insert("Hồ Ba Bể Bắc Kạn");
        trie.insert("Núi Lang Biang Lâm Đồng");
        trie.insert("Đầm Ô Loan Phú Yên");
        trie.insert("Đồi chè Tân Cương Thái Nguyên");
        trie.insert("Đồi chè Thanh Chương Nghệ An");
        trie.insert("Cánh đồng hoa hướng dương Nghệ An");
        trie.insert("Động Hương Tích Hà Nội");
        trie.insert("Cầu Thủ Thiêm Sài Gòn");
        trie.insert("Vườn quốc gia Yok Don Đắk Lắk");
        trie.insert("Bãi Đá Ông Địa Phan Thiết");
        trie.insert("Thác Đam Bri Lâm Đồng");
        trie.insert("Khu du lịch Cồn Phụng Bến Tre");
        trie.insert("Đồi chè Trái Tim Mộc Châu");
        trie.insert("Động Hoa Tiên Phong Nha");
        trie.insert("Công viên Suối Mơ Đồng Nai");
        trie.insert("Cồn Cỏ Quảng Trị");
        trie.insert("Làng chài Sơn Trà Đà Nẵng");
        trie.insert("Lăng vua Khải Định Huế");
        trie.insert("Vườn quốc gia Nam Cát Tiên");
        trie.insert("Cánh đồng cỏ lau Trà Vinh");
        trie.insert("Cù lao Thới Sơn");
        trie.insert("Đồi Chè Trái Tim Mộc Châu");
        trie.insert("Làng hoa Tân Quy Đông Sa Đéc");
        trie.insert("Suối nước nóng Bình Châu");
        trie.insert("Vườn quốc gia Núi Chúa");
        trie.insert("Làng chài Hàm Ninh Phú Quốc");
        trie.insert("Đầm Vân Long Ninh Bình");
        trie.insert("Đồi chè Mộc Châu Sơn La");
        trie.insert("Thác Cam Ly Đà Lạt");
        trie.insert("Khu du lịch Hồ Đa Tôn Đồng Nai");
        trie.insert("Làng nổi Tân Lập Long An");
        trie.insert("Vườn quốc gia Xuân Sơn Phú Thọ");
        trie.insert("Lăng vua Dục Đức Huế");
        trie.insert("Suối Mơ Bình Phước");
        trie.insert("Núi Sam Châu Đốc");
        trie.insert("Đồi Mâm Xôi Yên Bái");
        trie.insert("Chợ tình Khâu Vai Hà Giang");
        trie.insert("Đồi chè Cầu Đất Đà Lạt");
        trie.insert("Hòn Tre Nha Trang");
        trie.insert("Cồn Phụng Bến Tre");
        trie.insert("Chùa Tây Phương Hà Nội");
        trie.insert("Núi Bạch Mã Thừa Thiên Huế");
        trie.insert("Bảo tàng Dân tộc học Hà Nội");
        trie.insert("Đồng cừu Suối Nghệ Vũng Tàu");
        trie.insert("Biển Dốc Lết Khánh Hòa");
        trie.insert("Đảo Điệp Sơn Khánh Hòa");
        trie.insert("Công viên Suối Mơ Đồng Nai");
        trie.insert("Khu du lịch Hồ Mây Vũng Tàu");
        trie.insert("Cầu Rồng Đà Nẵng");
        trie.insert("Thác Pongour Lâm Đồng");
        trie.insert("Làng Cù Lần Đà Lạt");
        trie.insert("Chùa Thiên Hưng Bình Định");
        trie.insert("Đảo Bình Ba Khánh Hòa");
        trie.insert("Vịnh Vĩnh Hy Ninh Thuận");
        trie.insert("Đảo Yến Hòn Nội Khánh Hòa");
        trie.insert("Rừng nguyên sinh Rú Chá Thừa Thiên Huế");
        trie.insert("Tháp Po Klong Garai Ninh Thuận");
        trie.insert("Thác Bà Thanh Hóa");
        trie.insert("Núi Quan Ba Hà Giang");
        trie.insert("Làng cổ Đường Lâm Hà Nội");
        trie.insert("Làng dệt chiếu Định Yên Đồng Tháp");
        trie.insert("Làng nghề đúc đồng Phước Kiều Quảng Nam");
        trie.insert("Làng cổ Phước Tích Thừa Thiên Huế");
        trie.insert("Hồ Tuyền Lâm Đà Lạt");
        trie.insert("Hòn Dấu Hải Phòng");
        trie.insert("Hải Đăng Đại Lãnh Phú Yên");
        trie.insert("Khu du lịch Tràng An Ninh Bình");
        trie.insert("Cổng Trời Quản Bạ Hà Giang");
        trie.insert("Đỉnh Pha Luông Sơn La");
        trie.insert("Khu sinh thái Gò Cỏ Quảng Ngãi");
        trie.insert("Thác Đa Tân Giao Đồng Nai");
        trie.insert("Hồ Núi Cốc Thái Nguyên");
        trie.insert("Đồi cát Nam Cương Ninh Thuận");
        trie.insert("Đỉnh Phan Xi Păng Lào Cai");
        trie.insert("Hải đăng Kê Gà Bình Thuận");
        trie.insert("Bãi biển Non Nước Đà Nẵng");
        trie.insert("Biển Kỳ Co Quy Nhơn");
        trie.insert("Thành phố Lào Cai");
        trie.insert("Hang Múa Ninh Bình");
        trie.insert("Đảo Hòn Tằm Nha Trang");
        trie.insert("Suối nước nóng Hội Vân Bình Định");
        trie.insert("Núi Ngự Bình Thừa Thiên Huế");
        trie.insert("Chợ nổi Cái Bè Tiền Giang");
        trie.insert("Cù lao Chàm Quảng Nam");
        trie.insert("Tháp Bà Ponagar Nha Trang");
        trie.insert("Bãi biển Minh Châu Quảng Ninh");
        trie.insert("Chùa Dơi Sóc Trăng");
        trie.insert("Chùa Vĩnh Tràng Mỹ Tho");
        trie.insert("Chùa Hang An Giang");
        trie.insert("Vườn quốc gia Pù Mát Nghệ An");
        trie.insert("Vịnh Lan Hạ Hải Phòng");
        trie.insert("Núi Cô Tô Quảng Ninh");
        trie.insert("Biển Nhật Lệ Quảng Bình");
        trie.insert("Rừng quốc gia Yok Don Đắk Lắk");
        trie.insert("Chùa Phật Lớn Tây Ninh");
        trie.insert("Bãi Xép Phú Yên");
        trie.insert("Công viên văn hóa Đầm Sen Sài Gòn");
        trie.insert("Bảo tàng Lịch sử Quân sự Việt Nam");
        trie.insert("Suối khoáng nóng Tháp Bà Nha Trang");
        trie.insert("Khu du lịch Đại Nam Bình Dương");
        trie.insert("Rừng quốc gia Nam Cát Tiên Đồng Nai");
        trie.insert("Vườn quốc gia Ba Vì Hà Nội");
        trie.insert("Làng chài Vĩnh Hy Ninh Thuận");
        trie.insert("Chùa Tam Chúc Hà Nam");
        trie.insert("Cáp treo Bà Nà Đà Nẵng");
        trie.insert("Đảo Lý Sơn Quảng Ngãi");
        trie.insert("Suối Giải Mộc Châu");
        trie.insert("Đỉnh Tam Đảo Vĩnh Phúc");
        trie.insert("Khu du lịch Vinpearl Phú Quốc");
        trie.insert("Bảo tàng Tôn Đức Thắng An Giang");
        trie.insert("Đèo Pha Đin Sơn La");
        trie.insert("Lăng vua Gia Long Huế");
        trie.insert("Tháp Mười Đồng Tháp");
        trie.insert("Suối Tiên Sài Gòn");
        trie.insert("Hòn Rơm Mũi Né");
        trie.insert("Thác Yang Bay Khánh Hòa");
        trie.insert("Cao nguyên Mộc Châu Sơn La");
        trie.insert("Bãi Ông Lang Phú Quốc");
        trie.insert("Đồi Chè Đông Giang Quảng Nam");
        trie.insert("Núi Ba Vì Hà Nội");
        trie.insert("Đèo Ô Quy Hồ Lào Cai");
        trie.insert("Động Phong Nha Quảng Bình");
        trie.insert("Biển Lý Hòa Quảng Bình");
        trie.insert("Cồn cát Mũi Dinh Ninh Thuận");
        trie.insert("Làng thổ cẩm Chăm Mỹ Nghiệp");
        trie.insert("Suối nước nóng Bình Châu Vũng Tàu");
        trie.insert("Núi đá Mèo Vạc Hà Giang");
        trie.insert("Hải đăng Gành Đèn Phú Yên");
        trie.insert("Bãi biển Đại Lãnh Phú Yên");
        trie.insert("Bảo tàng Chăm Đà Nẵng");
        trie.insert("Đồi hoa hướng dương Nghệ An");
        trie.insert("Làng nghề Vạn Phúc Hà Đông");
        trie.insert("Suối nước nóng Thần Tài Đà Nẵng");
        trie.insert("Cồn Phụng Bến Tre");
        trie.insert("Bãi biển Bàu Trắng Bình Thuận");
        trie.insert("Chợ Đầm Nha Trang");
        trie.insert("Làng tranh Đông Hồ Bắc Ninh");
        trie.insert("Hồ Quan Sơn Hà Nội");

    }

    @Override
    public void addWord(String word) {
        trie.insert(word);
    }
    @Override
    public List<String> getSuggestions(String input) {
        return trie.autocomplete(input);
    }


}
